version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_PASSWORD: <db-password>
      DB_URL: <db-url>
      DB_USERNAME: <db-username>
      ADMIN_DEFAULT_USERNAME: admin
      ADMIN_DEFAULT_PASSWORD: admin
      TELEGRAM_BOT_USERNAME: <telegram-bot-username>
      TELEGRAM_BOT_TOKEN: <telegram-bot-token>
      APP_BASE_PATH: <app-base-path>
      TELEGRAM_BOT_URL_SECRET: "secret"