version: '3'
services:

  app:
    image: openjdk:8-jre-alpine
    ports:
      - 8080:8080
    environment:
      DB_PASSWORD: db_password
      DB_URL: jdbc:mysql://db/shpaltaif
      DB_USERNAME: db_user
      ADMIN_DEFAULT_USERNAME: admin
      ADMIN_DEFAULT_PASSWORD: admin
      TELEGRAM_BOT_USERNAME: <telegram-bot-username>
      TELEGRAM_BOT_TOKEN: <telegram-bot-token>
      TELEGRAM_BOT_URL_SECRET: "secret"
      APP_BASE_PATH: <app-base-path>
    volumes:
      - ./target:/target
    command: ["java", "-jar", "/target/shpalta-if-1.0.0.jar"]
    depends_on: 
      - db

  db:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: shpaltaif
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: 
    driver: local 