spring:
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/shpalta?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            missing_cache_strategy: create
    hibernate.ddl-auto: validate
  data:
    web.pageable.one-indexed-parameters: true

admin:
  default:
    username: ${ADMIN_DEFAULT_USERNAME:admin}
    password: ${ADMIN_DEFAULT_PASSWORD:admin}

telegrambot:
  username: ${TELEGRAM_BOT_USERNAME}
  token: ${TELEGRAM_BOT_TOKEN}
  url.secret: ${TELEGRAM_BOT_URL_SECRET}

app:
  base_path: ${APP_BASE_PATH}

