spring:
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/shpalta?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            missing_cache_strategy: create
    hibernate.ddl-auto: update

admin:
  default:
    login: ${ADMIN_DEFAULT_LOGIN:admin}
    password: ${ADMIN_DEFAULT_PASSWORD:admin}'
